debug

diff --git a/bin/supply b/bin/supply
--- a/bin/supply
+++ b/bin/supply
@@ -11,5 +11,20 @@ echo "CACHE_DIR: $CACHE_DIR"
 echo "DEPS_DIR: $DEPS_DIR"
 echo "DEPS_IDX $DEPS_IDX"
 
-#export BUILDPACK_DIR=`dirname $(readlink -f ${BASH_SOURCE%/*})`
-#python "$BUILDPACK_DIR/scripts/install_jmeter.py" $BUILD_DIR $CACHE_DIR $DEPS_DIR $DEPS_IDX
+# check if JQ exist?
+if ! [ -x "$(command -v jq)" ]; then
+  echo "Error: jq is not installed." >&2
+  exit 1
+fi
+
+# Download JMeter
+if [ ! -f $CACHE_DIR/apache-jmeter-5.1.1.tgz ]; then
+  echo "Downloading JMeter"
+  curl -L https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.5.tgz -o $CACHE_DIR/apache-jmeter-5.5.tgz
+fi
+
+# Extract JMeter
+if [ ! -d $DEPS_DIR/apache-jmeter-5.1.1 ]; then
+  echo "Extracting JMeter"
+  tar -xzf $CACHE_DIR/apache-jmeter-5.1.1.tgz -C $DEPS_DIR
+fi
